import { useState } from 'react';
import { useAuth } from './App';

// ── NAV (shared) ──
function Nav() {
  const { user, signIn, signOut } = useAuth();
  return (
    <nav className="bg-slate-900 text-white px-6 py-4 flex items-center justify-between sticky top-0 z-50">
      <a href="/" className="text-xl font-bold text-blue-400">NextEra Estate</a>
      <div className="flex items-center gap-4 text-sm">
        <a href="/" className="hover:text-blue-400">Home</a>
        <a href="/faq" className="hover:text-blue-400">FAQ</a>
        <a href="/terms" className="hover:text-blue-400">Terms</a>
        <a href="/privacy" className="hover:text-blue-400">Privacy</a>
        {user
          ? <button onClick={signOut} className="bg-slate-700 px-4 py-2 rounded hover:bg-slate-600">{user.name}</button>
          : <button onClick={signIn} className="bg-blue-600 px-4 py-2 rounded hover:bg-blue-700">Sign In</button>}
      </div>
    </nav>
  );
}

// ── TERMS OF SERVICE ──
export function TermsPage() {
  return (
    <div className="min-h-screen bg-slate-50">
      <Nav />
      <div className="max-w-4xl mx-auto px-6 py-16">
        <h1 className="text-4xl font-bold text-slate-900 mb-2">Terms of Service</h1>
        <p className="text-slate-500 mb-10">Last updated: March 2026 | Effective immediately upon use</p>

        <div className="bg-amber-50 border border-amber-200 rounded-xl p-5 mb-10">
          <p className="text-amber-800 text-sm font-medium">⚠️ IMPORTANT LEGAL NOTICE: NextEra Estate is a technology platform, not a law firm. We do not provide legal advice. All documents generated by our platform are for informational purposes only and must be reviewed by a licensed attorney before execution. Use of this platform does not create an attorney-client relationship.</p>
        </div>

        <div className="prose prose-slate max-w-none space-y-10">

          <section>
            <h2 className="text-2xl font-bold text-slate-800 mb-4">1. Acceptance of Terms</h2>
            <p className="text-slate-600 leading-relaxed">By accessing or using NextEra Estate ("the Platform," "we," "us," or "our"), operated by Pay Dirt Global LLC, you ("User," "you") agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, do not use the Platform. These Terms constitute a legally binding agreement between you and Pay Dirt Global LLC.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-800 mb-4">2. Not Legal Advice — Critical Disclaimer</h2>
            <div className="bg-red-50 border border-red-200 rounded-xl p-5 mb-4">
              <p className="text-red-800 font-semibold mb-2">READ THIS SECTION CAREFULLY</p>
              <ul className="text-red-700 text-sm space-y-2 list-disc pl-5">
                <li>NextEra Estate is NOT a law firm and does NOT provide legal advice.</li>
                <li>AI-generated documents, including wills, trusts, and directives, are NOT legal documents until properly executed according to your state's requirements.</li>
                <li>No attorney-client relationship is formed by using this Platform.</li>
                <li>Documents generated by this Platform may not comply with the laws of your specific jurisdiction without modification.</li>
                <li>You should consult a licensed attorney in your state before executing any document generated by this Platform.</li>
                <li>NextEra Estate, Pay Dirt Global LLC, and its affiliates are NOT responsible for the legal validity, enforceability, or consequences of any document created using this Platform.</li>
              </ul>
            </div>
            <p className="text-slate-600 leading-relaxed">The Platform provides general information about estate planning concepts and generates draft documents based on information you provide. This is not a substitute for professional legal counsel. Laws vary significantly by state and change frequently. Always verify current requirements with a licensed attorney.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-800 mb-4">3. Description of Services</h2>
            <p className="text-slate-600 leading-relaxed mb-3">NextEra Estate provides the following technology services:</p>
            <ul className="text-slate-600 space-y-2 list-disc pl-5">
              <li><strong>AI Will Builder:</strong> Generates draft will documents based on user-provided information using artificial intelligence.</li>
              <li><strong>Document Vault:</strong> Secure cloud storage for personal and estate planning documents.</li>
              <li><strong>Blockchain Notarization:</strong> Creates a cryptographic hash of documents recorded on the Polygon blockchain as a timestamping service. This is NOT a legal notarization by a licensed notary public.</li>
              <li><strong>Death Switch:</strong> An automated inactivity monitoring system that notifies designated contacts upon extended inactivity.</li>
              <li><strong>Video Messages:</strong> Storage and scheduled delivery of personal video messages.</li>
              <li><strong>Password Vault:</strong> Encrypted storage of account credentials and access information.</li>
              <li><strong>Compliance Center:</strong> General information about estate planning requirements by state. This information may not be current or complete.</li>
              <li><strong>Grief Counseling AI:</strong> AI-powered emotional support. This is NOT a licensed mental health service.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-800 mb-4">4. Blockchain Notarization Disclaimer</h2>
            <p className="text-slate-600 leading-relaxed">Our blockchain notarization service creates a SHA-256 cryptographic hash of your document recorded on the Polygon blockchain. This provides a tamper-evident timestamp but:</p>
            <ul className="text-slate-600 space-y-2 list-disc pl-5 mt-3">
              <li>Is NOT equivalent to notarization by a licensed notary public.</li>
              <li>Does NOT satisfy legal notarization requirements in any jurisdiction.</li>
              <li>Does NOT authenticate the identity of the document creator.</li>
              <li>Legal admissibility varies by jurisdiction and is not guaranteed.</li>
              <li>Blockchain immutability depends on the continued operation of the Polygon network, which we do not control.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-800 mb-4">5. Mental Health and Grief Counseling Disclaimer</h2>
            <div className="bg-blue-50 border border-blue-200 rounded-xl p-5 mb-4">
              <p className="text-blue-800 text-sm">If you are experiencing a mental health crisis, please contact the <strong>988 Suicide & Crisis Lifeline</strong> by calling or texting <strong>988</strong>. For emergencies, call <strong>911</strong>.</p>
            </div>
            <p className="text-slate-600 leading-relaxed">Our AI Grief Counseling feature provides general emotional support and is NOT:</p>
            <ul className="text-slate-600 space-y-2 list-disc pl-5 mt-3">
              <li>A licensed mental health service or therapy.</li>
              <li>A substitute for professional psychological or psychiatric care.</li>
              <li>Operated by licensed therapists, counselors, or mental health professionals.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-800 mb-4">6. User Responsibilities</h2>
            <p className="text-slate-600 leading-relaxed mb-3">You agree to:</p>
            <ul className="text-slate-600 space-y-2 list-disc pl-5">
              <li>Provide accurate and complete information when using the Platform.</li>
              <li>Maintain the confidentiality of your account credentials.</li>
              <li>Not use the Platform for any unlawful purpose.</li>
              <li>Not attempt to reverse engineer, hack, or compromise the Platform's security.</li>
              <li>Consult a licensed attorney before executing any documents generated by the Platform.</li>
              <li>Regularly review and update your estate planning documents to reflect changes in your circumstances or the law.</li>
              <li>Maintain your own backups of important documents.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-800 mb-4">7. Limitation of Liability</h2>
            <div className="bg-slate-100 rounded-xl p-5">
              <p className="text-slate-700 font-semibold mb-3">TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW:</p>
              <p className="text-slate-600 text-sm leading-relaxed mb-3">PAY DIRT GLOBAL LLC, NEXTERA ESTATE, AND THEIR OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, AND AFFILIATES SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO:</p>
              <ul className="text-slate-600 text-sm space-y-1 list-disc pl-5">
                <li>Invalid, unenforceable, or contested estate planning documents.</li>
                <li>Loss of data, documents, or stored information.</li>
                <li>Failure of the Death Switch to operate as intended.</li>
                <li>Incorrect, incomplete, or outdated legal compliance information.</li>
                <li>Any reliance on AI-generated content without independent legal verification.</li>
                <li>Unauthorized access to your account or Password Vault.</li>
                <li>Failure of blockchain notarization to be recognized in legal proceedings.</li>
                <li>Any estate planning outcome regardless of cause.</li>
              </ul>
              <p className="text-slate-600 text-sm mt-3">OUR TOTAL LIABILITY SHALL NOT EXCEED THE AMOUNT YOU PAID US IN THE 12 MONTHS PRECEDING THE CLAIM.</p>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-800 mb-4">8. Data and Privacy</h2>
            <p className="text-slate-600 leading-relaxed">Your use of the Platform is also governed by our Privacy Policy. You acknowledge that estate planning information is highly sensitive. While we implement industry-standard security measures, no system is completely secure. You use the Platform at your own risk.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-800 mb-4">9. Subscription and Payments</h2>
            <ul className="text-slate-600 space-y-2 list-disc pl-5">
              <li>Subscriptions are billed monthly or annually as selected.</li>
              <li>Cancellation takes effect at the end of the current billing period.</li>
              <li>No refunds are provided for partial billing periods.</li>
              <li>We reserve the right to change pricing with 30 days notice.</li>
              <li>Free tier features may change at any time.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-800 mb-4">10. Intellectual Property</h2>
            <p className="text-slate-600 leading-relaxed">You retain ownership of content you create using the Platform. You grant Pay Dirt Global LLC a limited license to store, process, and display your content solely to provide the Platform's services. AI-generated document templates and Platform content are owned by Pay Dirt Global LLC.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-800 mb-4">11. Termination</h2>
            <p className="text-slate-600 leading-relaxed">We may terminate or suspend your account at any time for violation of these Terms. Upon termination, you have 30 days to export your data before it is deleted. You may cancel your account at any time through your account settings.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-800 mb-4">12. Governing Law and Disputes</h2>
            <p className="text-slate-600 leading-relaxed">These Terms are governed by the laws of the State of Alabama. Any disputes shall be resolved by binding arbitration in Tuscaloosa County, Alabama, under the rules of the American Arbitration Association. You waive the right to participate in class action lawsuits.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-800 mb-4">13. Changes to Terms</h2>
            <p className="text-slate-600 leading-relaxed">We may update these Terms at any time. Continued use of the Platform after changes constitutes acceptance. We will provide 30 days notice of material changes via email.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-800 mb-4">14. Contact</h2>
            <p className="text-slate-600">Pay Dirt Global LLC | NextEra Estate<br />Email: <a href="mailto:legal@nexteraestate.com" className="text-blue-600">legal@nexteraestate.com</a><br />Northport, Alabama</p>
          </section>

        </div>
      </div>
    </div>
  );
}

// ── PRIVACY POLICY ──
export function PrivacyPage() {
  return (
    <div className="min-h-screen bg-slate-50">
      <Nav />
      <div className="max-w-4xl mx-auto px-6 py-16">
        <h1 className="text-4xl font-bold text-slate-900 mb-2">Privacy Policy</h1>
        <p className="text-slate-500 mb-10">Last updated: March 2026</p>

        <div className="prose prose-slate max-w-none space-y-10">
          <section>
            <h2 className="text-2xl font-bold text-slate-800 mb-4">1. Information We Collect</h2>
            <ul className="text-slate-600 space-y-2 list-disc pl-5">
              <li><strong>Account Information:</strong> Name, email address via Google OAuth.</li>
              <li><strong>Estate Planning Data:</strong> Information you enter into the Will Builder, Document Vault, and other features.</li>
              <li><strong>Password Vault Data:</strong> Encrypted credentials and access information you store.</li>
              <li><strong>Usage Data:</strong> How you interact with the Platform.</li>
              <li><strong>Payment Information:</strong> Processed by Stripe — we do not store card numbers.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-800 mb-4">2. How We Use Your Information</h2>
            <ul className="text-slate-600 space-y-2 list-disc pl-5">
              <li>To provide and improve Platform services.</li>
              <li>To generate AI-assisted estate planning documents.</li>
              <li>To operate the Death Switch notification system.</li>
              <li>To deliver video messages to designated recipients.</li>
              <li>To communicate service updates and billing information.</li>
              <li>We do NOT sell your personal information to third parties.</li>
              <li>We do NOT use your estate planning data for advertising.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-800 mb-4">3. Data Security</h2>
            <p className="text-slate-600 leading-relaxed">We use industry-standard encryption for data in transit (TLS) and at rest. Password Vault entries are encrypted before storage. However, no system is 100% secure and we cannot guarantee absolute security of your data.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-800 mb-4">4. Data Retention and Deletion</h2>
            <p className="text-slate-600 leading-relaxed">Your data is retained while your account is active. Upon account deletion, your data is permanently deleted within 30 days. Blockchain notarization hashes, once recorded on the Polygon network, cannot be deleted as they are part of a public, immutable blockchain.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-800 mb-4">5. Third-Party Services</h2>
            <ul className="text-slate-600 space-y-2 list-disc pl-5">
              <li><strong>Google OAuth:</strong> For authentication — governed by Google's Privacy Policy.</li>
              <li><strong>Anthropic Claude AI:</strong> Processes your inputs to generate estate planning documents.</li>
              <li><strong>Neon Database:</strong> Secure cloud database storage.</li>
              <li><strong>Stripe:</strong> Payment processing.</li>
              <li><strong>Polygon Blockchain:</strong> Public blockchain for notarization hashes.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-800 mb-4">6. Your Rights</h2>
            <p className="text-slate-600 leading-relaxed">You may request access to, correction of, or deletion of your personal data by contacting us at <a href="mailto:privacy@nexteraestate.com" className="text-blue-600">privacy@nexteraestate.com</a>.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-800 mb-4">7. Contact</h2>
            <p className="text-slate-600">Email: <a href="mailto:privacy@nexteraestate.com" className="text-blue-600">privacy@nexteraestate.com</a></p>
          </section>
        </div>
      </div>
    </div>
  );
}

// ── FAQ PAGE ──
const faqs = [
  {
    category: 'General',
    questions: [
      {
        q: 'Is NextEra Estate a law firm?',
        a: 'No. NextEra Estate is a technology platform operated by Pay Dirt Global LLC. We are not a law firm and do not provide legal advice. Documents generated by our platform are drafts for your review and should be reviewed by a licensed attorney before execution.'
      },
      {
        q: 'Is a will created on NextEra Estate legally valid?',
        a: 'A will draft generated by our AI is not automatically legally valid. To be valid, a will must be properly executed according to your state\'s requirements — typically signed by you and witnessed by two adult non-beneficiary witnesses. Some states require notarization. Always have your will reviewed and executed with an attorney\'s guidance.'
      },
      {
        q: 'What states do you support?',
        a: 'We provide compliance information and will drafts for all 50 US states. However, laws vary significantly by state and change frequently. Our AI is trained on general estate planning law but may not reflect the most current state-specific requirements. Always verify with a local attorney.'
      },
      {
        q: 'How is my data protected?',
        a: 'Your data is encrypted in transit using TLS and at rest in our database. Password Vault entries are encrypted before storage. We use Neon, a SOC 2 compliant database provider. We never sell your data or use it for advertising.'
      },
    ]
  },
  {
    category: 'Will Builder',
    questions: [
      {
        q: 'How does the AI Will Builder work?',
        a: 'You complete a 7-step form providing information about yourself, your executor, beneficiaries, assets, and final wishes. Our AI (powered by Anthropic\'s Claude) generates a complete draft will document based on your inputs and your state\'s general requirements.'
      },
      {
        q: 'Do I need an attorney to use the Will Builder?',
        a: 'You don\'t need an attorney to create a draft, but we strongly recommend consulting one before signing. A licensed estate planning attorney can identify issues specific to your situation, ensure compliance with current state law, and witness or notarize your execution.'
      },
      {
        q: 'What happens to my will if I update my assets or family situation?',
        a: 'You can return to the Will Builder at any time to create an updated draft. Keep in mind that an updated will must be re-executed with proper witnesses to replace your previous will. Inform your executor whenever you create a new version.'
      },
      {
        q: 'Can I create a will for my spouse too?',
        a: 'On our Legacy plan, you can manage multiple wills within your account for family members. Each person should have their own separately executed will. Our platform helps draft them but each must be individually signed and witnessed.'
      },
    ]
  },
  {
    category: 'Blockchain Notarization',
    questions: [
      {
        q: 'What is blockchain notarization?',
        a: 'Our blockchain notarization creates a SHA-256 cryptographic hash (a unique digital fingerprint) of your document and records it on the Polygon blockchain with a timestamp. This proves your document existed in its current form at a specific point in time.'
      },
      {
        q: 'Is blockchain notarization the same as legal notarization?',
        a: 'No. Blockchain notarization is NOT the same as notarization by a licensed notary public, which verifies identity and witnesses signatures. Our service provides timestamping only. It does not satisfy legal notarization requirements for wills, deeds, or other documents that require notarization by law.'
      },
      {
        q: 'Is blockchain notarization admissible in court?',
        a: 'The legal admissibility of blockchain records varies by jurisdiction and is an evolving area of law. Some states have enacted legislation recognizing blockchain records as evidence. Consult an attorney regarding admissibility in your state.'
      },
      {
        q: 'Can I delete a blockchain notarization?',
        a: 'No. Once recorded on the Polygon blockchain, a transaction cannot be deleted. The blockchain is designed to be permanent and immutable. Only the hash (digital fingerprint) is recorded — not the document content itself.'
      },
    ]
  },
  {
    category: 'Death Switch',
    questions: [
      {
        q: 'How does the Death Switch work?',
        a: 'The Death Switch monitors your account activity. If you don\'t log in within your set inactivity period (30-365 days), the system sends warning emails to you first. If you still don\'t respond, it notifies your designated heirs and releases your designated documents to your executor.'
      },
      {
        q: 'What triggers the Death Switch?',
        a: 'The Death Switch triggers after your set inactivity period expires without a check-in. You can check in simply by logging into your account. We also send warning emails before triggering so you have a chance to reset the timer.'
      },
      {
        q: 'Is the Death Switch guaranteed to work?',
        a: 'No system can be guaranteed. The Death Switch depends on the continued operation of the NextEra Estate platform and your heirs having valid email addresses. Do not rely solely on this system — always ensure your executor knows the location of your physical estate planning documents.'
      },
      {
        q: 'Can my heirs access my Password Vault through the Death Switch?',
        a: 'On our Complete and Legacy plans, you can designate which information is released upon Death Switch activation. Your executor will receive instructions and access credentials that you specify in advance.'
      },
    ]
  },
  {
    category: 'Social Security & Veterans Benefits',
    questions: [
      {
        q: 'What is the Social Security Survivors Benefit?',
        a: 'Social Security Survivors Benefits are monthly payments to eligible family members of a deceased worker who paid into Social Security. Eligible survivors may include a spouse (as early as age 60, or 50 if disabled), a spouse caring for children under 16, unmarried children under 18 (or 19 if still in school), and disabled children. The benefit amount depends on the deceased\'s earning record. Apply at ssa.gov or call 1-800-772-1213.'
      },
      {
        q: 'How do I apply for Social Security Survivors Benefits?',
        a: 'You cannot apply for survivors benefits online. Call the Social Security Administration at 1-800-772-1213 or visit your local SSA office. You will need: the deceased\'s Social Security number, your birth certificate, marriage certificate (if applying as a spouse), and the deceased\'s most recent W-2 or tax return. Apply as soon as possible — benefits are not retroactive beyond the application month.'
      },
      {
        q: 'What VA benefits are available to surviving family members?',
        a: 'Veterans\' surviving family members may be eligible for: Dependency and Indemnity Compensation (DIC) — monthly payments to surviving spouses, children, and parents of veterans who died from service-connected conditions; VA Survivors Pension — for low-income surviving spouses and children of wartime veterans; CHAMPVA — health insurance for survivors; and Burial Benefits — for eligible veterans. Visit va.gov/burials-memorials/veterans-burial-allowance or call 1-800-827-1000.'
      },
      {
        q: 'What is Dependency and Indemnity Compensation (DIC)?',
        a: 'DIC is a tax-free monetary benefit paid to eligible survivors of military service members who died in the line of duty, or veterans who died from a service-connected illness or injury. The surviving spouse must have been married to the veteran for at least one year (or have children together). The base rate is adjusted annually. Apply with VA Form 21P-534EZ at va.gov.'
      },
      {
        q: 'Can a surviving spouse receive both Social Security and VA benefits?',
        a: 'Yes. Social Security Survivors Benefits and VA benefits (DIC, Survivors Pension) are separate programs and can generally be received simultaneously. They are not offset against each other. However, VA Survivors Pension (unlike DIC) is means-tested and factors in other income including Social Security.'
      },
    ]
  },
  {
    category: 'Pricing & Account',
    questions: [
      {
        q: 'What is included in the free plan?',
        a: 'The free plan includes dashboard access, 1 will draft (watermarked), 5 Esquire AI questions per month, and 1 document in the vault. It\'s designed to let you explore the platform before committing to a subscription.'
      },
      {
        q: 'Can I cancel my subscription at any time?',
        a: 'Yes. You can cancel at any time through your account settings. Your subscription remains active until the end of the current billing period. We do not provide refunds for partial periods.'
      },
      {
        q: 'What happens to my data if I cancel?',
        a: 'Your data remains accessible for 30 days after cancellation. During that time, you can export your documents and will drafts. After 30 days, your data is permanently deleted.'
      },
      {
        q: 'Is my payment information secure?',
        a: 'Yes. Payment processing is handled entirely by Stripe, a PCI-compliant payment processor. We never store your credit card number on our servers.'
      },
    ]
  },
];

export function FAQPage() {
  const [openItem, setOpenItem] = useState<string | null>(null);
  const [activeCategory, setActiveCategory] = useState('All');

  const categories = ['All', ...faqs.map(f => f.category)];
  const filtered = activeCategory === 'All' ? faqs : faqs.filter(f => f.category === activeCategory);

  return (
    <div className="min-h-screen bg-slate-50">
      <Nav />
      <div className="max-w-4xl mx-auto px-6 py-16">
        <h1 className="text-4xl font-bold text-slate-900 mb-2">Frequently Asked Questions</h1>
        <p className="text-slate-500 mb-10">Everything you need to know about NextEra Estate, estate planning, and survivor benefits.</p>

        <div className="flex flex-wrap gap-2 mb-10">
          {categories.map(c => (
            <button key={c} onClick={() => setActiveCategory(c)} className={`px-4 py-2 rounded-full text-sm font-medium transition-colors ${activeCategory === c ? 'bg-slate-900 text-white' : 'bg-white border border-slate-200 text-slate-600 hover:border-slate-400'}`}>{c}</button>
          ))}
        </div>

        <div className="space-y-8">
          {filtered.map(section => (
            <div key={section.category}>
              <h2 className="text-xl font-bold text-slate-800 mb-4">{section.category}</h2>
              <div className="space-y-3">
                {section.questions.map((item, i) => {
                  const key = section.category + i;
                  const isOpen = openItem === key;
                  return (
                    <div key={key} className="bg-white rounded-xl border border-slate-200 overflow-hidden">
                      <button onClick={() => setOpenItem(isOpen ? null : key)} className="w-full px-6 py-4 text-left flex items-center justify-between gap-4">
                        <span className="font-medium text-slate-800 text-sm">{item.q}</span>
                        <span className={`text-slate-400 text-lg flex-shrink-0 transition-transform ${isOpen ? 'rotate-45' : ''}`}>+</span>
                      </button>
                      {isOpen && (
                        <div className="px-6 pb-5">
                          <p className="text-slate-600 text-sm leading-relaxed">{item.a}</p>
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            </div>
          ))}
        </div>

        <div className="mt-16 bg-blue-50 border border-blue-100 rounded-2xl p-8 text-center">
          <h3 className="text-xl font-bold text-slate-800 mb-2">Still have questions?</h3>
          <p className="text-slate-500 mb-4 text-sm">Our Esquire AI can answer most estate planning questions instantly.</p>
          <a href="/dashboard" className="bg-blue-600 text-white px-6 py-3 rounded-xl hover:bg-blue-700 inline-block font-semibold">Ask Esquire AI</a>
        </div>
      </div>
    </div>
  );
}
